### ISSUE TITLE
web zh-cn messy code

### ISSUE THREAD

**Issue by yyjazsf** [fontforge/designwithfontforge.com#140]
system: osx 10.12.2
browser :chrome

## descript
Due to the style:
```css
#main-content h1, #main-content h2, h3, h4, h5, h6, #sidebar{
  font-family: 'Source Sans Pro', sans-serif;
  font-weight: 700;
}
```
